version: "3.9"
services:
  app:
    # 根據當前目錄尋找名為 Dockerfile 文件建立容器
    build:
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    restart: on-failure
    ports:
      - 3000:3000
  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}